set(_CATKIN_CURRENT_PACKAGE "chatapp")
set(chatapp_VERSION "0.0.0")
set(chatapp_MAINTAINER "Priyanshu Sharma <priyanshusharma1803@outlook.com>")
set(chatapp_PACKAGE_FORMAT "2")
set(chatapp_BUILD_DEPENDS "roscpp" "rospy" "std_msgs")
set(chatapp_BUILD_EXPORT_DEPENDS "roscpp" "rospy" "std_msgs")
set(chatapp_BUILDTOOL_DEPENDS "catkin")
set(chatapp_BUILDTOOL_EXPORT_DEPENDS )
set(chatapp_EXEC_DEPENDS "roscpp" "rospy" "std_msgs")
set(chatapp_RUN_DEPENDS "roscpp" "rospy" "std_msgs")
set(chatapp_TEST_DEPENDS )
set(chatapp_DOC_DEPENDS )
set(chatapp_URL_WEBSITE "")
set(chatapp_URL_BUGTRACKER "")
set(chatapp_URL_REPOSITORY "")
set(chatapp_DEPRECATED "")